const FILE_SERVER_FOLDER_PATH_KEY = "fileServerFolderPath";
const ALLOWED_REMOTE_READ_KEY = "allowedRemoteRead";
const ALLOWED_OVERWRITE_KEY = "allowedOverwrite";
const SD_WEB_UI_SCRIPT_PATH_KEY = "sdWebUIScriptPath";

export { FILE_SERVER_FOLDER_PATH_KEY, ALLOWED_REMOTE_READ_KEY, ALLOWED_OVERWRITE_KEY, SD_WEB_UI_SCRIPT_PATH_KEY };